"""
Camera module for Minecraft AI.

Captures first-person screenshots from the bot's viewpoint using
prismarine-viewer and Three.js rendering via JSPyBridge.
"""

import os
import asyncio
from typing import Optional
from datetime import datetime

from javascript import require, On

from utils import add_log

# Global flag to track if helper modules have been set up
_globals_initialized = False
_canvas_helper_loaded = False

# Path for the globals helper file (in project directory)
# Use .cjs extension because package.json has "type": "module"
_GLOBALS_JS_FILENAME = '.camera_globals_helper.cjs'
_CANVAS_HELPER_FILENAME = '.camera_canvas_helper.cjs'

# Store the canvas createCanvas function after loading
_createCanvas_func = None

# Keep module reference alive for JSPyBridge
# JSPyBridge uses ffid (foreign function ID) to track objects.
# If we store helper.createCanvas directly without keeping helper alive,
# the ffid may become stale if helper gets garbage collected.
_canvas_helper_module = None


def _ensure_globals():
    """Set up global variables for Three.js/prismarine-viewer.

    This must be called before loading prismarine-viewer components.
    We create a JavaScript file in the project directory that sets:
    - globalThis.Worker (for Three.js web workers)
    - globalThis.THREE (for prismarine-viewer entities)
    """
    global _globals_initialized

    if _globals_initialized:
        return

    # Create a JavaScript file to set up the globals
    # Using CommonJS syntax with .cjs extension
    js_code = '''// Auto-generated by camera.py - do not edit
const { Worker } = require('worker_threads');
const THREE = require('three');

// Set globals that prismarine-viewer expects
globalThis.Worker = Worker;
globalThis.THREE = THREE;

module.exports = { Worker, THREE };
'''

    # Write to the project directory (same directory as this file)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    js_file = os.path.join(script_dir, _GLOBALS_JS_FILENAME)

    try:
        # Remove old helper file first to avoid caching issues
        if os.path.exists(js_file):
            os.remove(js_file)

        with open(js_file, 'w') as f:
            f.write(js_code)

        # Use relative path for require
        require(f'./{_GLOBALS_JS_FILENAME}')
        _globals_initialized = True
        add_log(
            title="[Camera] Globals initialized",
            content="globalThis.Worker and globalThis.THREE set successfully",
            label="success"
        )
    except Exception as e:
        add_log(
            title="[Camera] Failed to initialize globals",
            content=f"Exception: {str(e)}",
            label="warning"
        )
        # Continue anyway - might work in some cases


def _load_canvas_helper():
    """Load canvas module via a JavaScript helper file.

    JSPyBridge has issues loading native modules like node-canvas-webgl directly.
    We use a helper file that Node.js loads natively, which properly handles
    the native bindings.

    IMPORTANT: We keep a reference to the helper module at module level to prevent
    JSPyBridge from garbage collecting it. If we only stored helper.createCanvas,
    the ffid (foreign function ID) would reference the parent object (helper),
    which could be garbage collected, causing subsequent calls to fail with:
    "Cannot read properties of undefined (reading 'createCanvas')"
    """
    global _canvas_helper_loaded, _createCanvas_func, _canvas_helper_module

    if _canvas_helper_loaded:
        return _createCanvas_func

    script_dir = os.path.dirname(os.path.abspath(__file__))
    helper_file = os.path.join(script_dir, _CANVAS_HELPER_FILENAME)

    # Create the helper JavaScript file
    # This file is loaded by Node.js which properly handles native modules
    js_code = '''// Auto-generated by camera.py - do not edit
// This helper loads node-canvas-webgl which has native bindings
// JSPyBridge can't load native modules directly, so we use this workaround

let _createCanvas = null;
let loadError = null;

try {
    // Try node-canvas-webgl first (has WebGL support)
    const canvasWebgl = require('node-canvas-webgl');
    if (canvasWebgl && typeof canvasWebgl.createCanvas === 'function') {
        _createCanvas = canvasWebgl.createCanvas;
        console.log('[Camera Helper] Loaded node-canvas-webgl successfully');
    } else {
        loadError = 'node-canvas-webgl.createCanvas is not a function';
    }
} catch (e) {
    loadError = 'node-canvas-webgl: ' + e.message;
    try {
        // Fallback to native canvas package
        const canvas = require('canvas');
        if (canvas && typeof canvas.createCanvas === 'function') {
            _createCanvas = canvas.createCanvas;
            console.log('[Camera Helper] Loaded canvas package successfully');
        } else {
            loadError = 'canvas.createCanvas is not a function';
        }
    } catch (e2) {
        loadError = 'canvas: ' + e2.message;
    }
}

// Verify _createCanvas is actually callable
if (typeof _createCanvas !== 'function') {
    console.error('[Camera Helper] createCanvas is not a function:', typeof _createCanvas);
    console.error('[Camera Helper] Load error:', loadError);
    _createCanvas = null;
}

// Export a wrapper function that JSPyBridge can call properly
function createCanvas(width, height) {
    if (!_createCanvas) {
        throw new Error('Canvas module not loaded: ' + loadError);
    }
    return _createCanvas(width, height);
}

module.exports = { createCanvas, loadError, isLoaded: _createCanvas !== null };
'''

    try:
        # Remove old helper file first to avoid caching issues
        if os.path.exists(helper_file):
            os.remove(helper_file)

        with open(helper_file, 'w') as f:
            f.write(js_code)

        # Load the helper via JSPyBridge
        helper = require(f'./{_CANVAS_HELPER_FILENAME}')

        # CRITICAL: Keep module reference alive at module level!
        # This prevents JSPyBridge from garbage collecting the helper module,
        # which would invalidate the ffid used to call createCanvas.
        _canvas_helper_module = helper

        _canvas_helper_loaded = True

        # Check if the module loaded successfully
        is_loaded = False
        try:
            is_loaded = helper.isLoaded
        except Exception:
            pass

        # Check if loadError exists
        try:
            load_error = helper.loadError
            if load_error:
                add_log(
                    title="[Camera] Canvas module load error",
                    content=f"Error: {load_error}",
                    label="warning"
                )
        except Exception:
            pass

        # Only use createCanvas if the module is loaded
        if is_loaded and helper.createCanvas is not None:
            # Create a wrapper function that accesses createCanvas through
            # the live module reference. This ensures the ffid stays valid.
            def createCanvas_wrapper(width, height):
                return _canvas_helper_module.createCanvas(width, height)

            _createCanvas_func = createCanvas_wrapper
            add_log(
                title="[Camera] Canvas helper loaded",
                content="createCanvas function available (with module reference)",
                label="success"
            )
        else:
            add_log(
                title="[Camera] Canvas helper failed",
                content="createCanvas not available - vision will be disabled",
                label="error"
            )
            _createCanvas_func = None

        return _createCanvas_func
    except Exception as e:
        add_log(
            title="[Camera] Failed to load canvas helper",
            content=f"Exception: {str(e)}",
            label="error"
        )
        return None


class Camera:
    """Manages first-person screenshot capture via prismarine-viewer."""

    def __init__(self, bot, screenshot_dir: str):
        """Initialize the camera.

        Args:
            bot: The mineflayer bot instance (from JSPyBridge)
            screenshot_dir: Directory path for saving screenshots
        """
        self.bot = bot
        self.screenshot_dir = screenshot_dir
        self.ready = False
        self._initialized = False
        self._init_attempted = False

        # Camera settings
        self.view_distance = 12
        self.width = 800
        self.height = 512

        # JavaScript objects (initialized in _init)
        self.canvas = None
        self.renderer = None
        self.viewer = None
        self.world_view = None

        # Import required JavaScript modules
        self._import_js_modules()

        add_log(
            title="[Camera] Camera created",
            content="Will initialize when bot spawns",
            label="agent"
        )

        # Try immediate initialization if bot already spawned
        self._try_init()

        # Also listen for spawn events to initialize when bot (re)spawns
        @On(self.bot, 'spawn')
        def on_camera_spawn(*args):
            self._try_init()

    def _try_init(self):
        """Try to initialize if bot has spawned."""
        if self._initialized:
            return

        if self._init_attempted:
            return

        if self.bot.entity is None:
            add_log(
                title="[Camera] Bot not spawned yet",
                content="Waiting for bot entity...",
                label="agent"
            )
            return

        add_log(
            title="[Camera] Bot spawned, initializing...",
            content=f"Bot position: {self.bot.entity.position}",
            label="agent"
        )
        self._init_attempted = True
        self._init()

    def _import_js_modules(self):
        """Import required JavaScript modules via JSPyBridge.

        IMPORTANT: We store module references and access functions/classes through them
        to prevent JSPyBridge from garbage collecting the parent modules. If we only
        store extracted function references (like .Viewer, .getBufferFromStream), the
        ffid becomes stale when the parent module is garbage collected.
        """
        try:
            # First, set up globals (Worker, THREE) before loading prismarine-viewer
            _ensure_globals()

            # Import Three.js and related modules
            # Store module references for classes accessed via .new()
            self._three_module = require('three')
            self.THREE = self._three_module

            self._vec3_module = require('vec3')
            self.Vec3 = self._vec3_module.Vec3

            self._events_module = require('events')
            self.EventEmitter = self._events_module.EventEmitter

            # Load canvas via helper (handles native module loading issues)
            self.createCanvas = _load_canvas_helper()
            if self.createCanvas is None:
                raise RuntimeError("Failed to load canvas module - cannot create screenshots")

            # Import prismarine-viewer components - keep module references alive!
            self._viewer_module = require('prismarine-viewer/viewer/lib/viewer.js')
            self.Viewer = self._viewer_module.Viewer

            self._worldview_module = require('prismarine-viewer/viewer/lib/worldview.js')
            self.WorldView = self._worldview_module.WorldView

            self._simpleutils_module = require('prismarine-viewer/viewer/lib/simpleUtils.js')
            # Store module reference, access getBufferFromStream through it
            self._getBufferFromStream = self._simpleutils_module.getBufferFromStream

            # Import fs for file operations
            self.fs = require('fs/promises')

            add_log(
                title="[Camera] JavaScript modules imported",
                content="All required modules loaded successfully",
                label="success"
            )
        except Exception as e:
            add_log(
                title="[Camera] Failed to import JavaScript modules",
                content=f"Exception: {str(e)}",
                label="error"
            )
            raise

    def _init(self):
        """Initialize the camera renderer and world view.

        This is called after the bot has spawned.
        """
        if self._initialized:
            return  # Already initialized

        self._initialized = True
        add_log(
            title="[Camera] Starting initialization",
            content="Creating canvas and renderer...",
            label="agent"
        )

        try:
            # Check if createCanvas is available
            if self.createCanvas is None:
                add_log(
                    title="[Camera] Cannot initialize - no canvas function",
                    content="createCanvas is None, vision will be disabled",
                    label="error"
                )
                return

            # Create canvas and renderer
            add_log(
                title="[Camera] Calling createCanvas",
                content=f"Size: {self.width}x{self.height}",
                label="agent"
            )
            self.canvas = self.createCanvas(self.width, self.height)

            if self.canvas is None:
                add_log(
                    title="[Camera] Canvas creation returned None",
                    content="The createCanvas function returned null",
                    label="error"
                )
                return

            add_log(
                title="[Camera] Canvas object created",
                content=f"Type: {type(self.canvas)}",
                label="agent"
            )

            self.renderer = self._three_module.WebGLRenderer.new({"canvas": self.canvas})
            self.renderer.setSize(self.width, self.height)

            add_log(
                title="[Camera] Canvas created",
                content=f"Size: {self.width}x{self.height}",
                label="agent"
            )

            # Create viewer - access through module reference to keep ffid valid
            self.viewer = self._viewer_module.Viewer.new(self.renderer)
            self.viewer.setVersion(self.bot.version)

            add_log(
                title="[Camera] Viewer created",
                content=f"Version: {self.bot.version}",
                label="agent"
            )

            # Get bot position for initial world view
            bot_pos = self.bot.entity.position
            center = self._vec3_module.Vec3(
                bot_pos.x,
                bot_pos.y + self.bot.entity.height,
                bot_pos.z
            )

            add_log(
                title="[Camera] Creating world view",
                content=f"Center: ({bot_pos.x:.1f}, {bot_pos.y:.1f}, {bot_pos.z:.1f})",
                label="agent"
            )

            # Create and initialize world view - access through module reference
            self.world_view = self._worldview_module.WorldView.new(
                self.bot.world,
                self.view_distance,
                center
            )
            self.viewer.listen(self.world_view)
            # Note: We skip listenToBot() to avoid "Unknown entity" errors
            # This means entities won't be rendered, but world blocks will still show
            # and screenshots will work fine for object detection
            # self.world_view.listenToBot(self.bot)

            # Initialize world view asynchronously
            self._init_world_view(center)

        except Exception as e:
            add_log(
                title="[Camera] Initialization failed",
                content=f"Exception: {str(e)}",
                label="error"
            )

    def _init_world_view(self, center):
        """Initialize world view - simplified synchronous version."""
        try:
            # Try to call init if it exists, but don't wait for async
            try:
                init_result = self.world_view.init(center)
                # Ignore the result - world_view will initialize when needed
            except Exception:
                pass  # init() might not exist or might fail, that's OK

            # Mark as ready immediately
            self.ready = True
            add_log(
                title="[Camera] Initialized successfully",
                content="Ready to capture screenshots",
                label="success"
            )
        except Exception as e:
            add_log(
                title="[Camera] World view initialization failed",
                content=f"Exception: {str(e)}",
                label="error"
            )

    async def capture(self) -> Optional[str]:
        """Capture a screenshot from the bot's first-person view.

        Returns:
            The filename (without extension) of the captured screenshot, or None on failure
        """
        if not self.ready:
            add_log(
                title="[Camera] Capture called before initialization complete",
                content="Camera not ready",
                label="warning"
            )
            return None

        try:
            # Update camera position to bot's current position
            bot_pos = self.bot.entity.position
            center = self._vec3_module.Vec3(
                bot_pos.x,
                bot_pos.y + self.bot.entity.height,
                bot_pos.z
            )

            self.viewer.camera.position.set(center.x, center.y, center.z)

            # Update world view position (may or may not be async)
            # Use try/except instead of hasattr for JSPyBridge Proxy objects
            try:
                update_result = self.world_view.updatePosition(center)
                if update_result is not None:
                    try:
                        await update_result
                    except TypeError:
                        # Not awaitable, ignore
                        pass
            except Exception:
                pass

            # Set first-person camera with bot's current rotation
            self.viewer.setFirstPersonCamera(
                self.bot.entity.position,
                self.bot.entity.yaw,
                self.bot.entity.pitch
            )

            # Update and render
            self.viewer.update()
            self.renderer.render(self.viewer.scene, self.viewer.camera)

            # Create JPEG stream
            image_stream = self.canvas.createJPEGStream({
                "bufsize": 4096,
                "quality": 90,
                "progressive": False
            })

            # Generate filename with timestamp
            timestamp = datetime.now().isoformat().replace(":", "-").replace(".", "-")
            filename = f"screenshot_{timestamp}"

            # Ensure directory exists
            await self._ensure_screenshot_directory()

            # Get buffer from stream and write to file
            # Access through module reference to keep ffid valid
            buf = None
            try:
                buf_result = self._simpleutils_module.getBufferFromStream(image_stream)
                if buf_result is not None:
                    try:
                        buf = await buf_result
                    except TypeError:
                        # Not awaitable, use directly
                        buf = buf_result
            except Exception as e:
                add_log(
                    title="[Camera] Buffer stream error",
                    content=f"Exception: {str(e)}",
                    label="warning"
                )
                return None

            if buf is None:
                add_log(
                    title="[Camera] No buffer from stream",
                    content="getBufferFromStream returned None",
                    label="warning"
                )
                return None

            try:
                write_result = self.fs.writeFile(f"{self.screenshot_dir}/{filename}.jpg", buf)
                if write_result is not None:
                    try:
                        await write_result
                    except TypeError:
                        # Not awaitable, ignore
                        pass
            except Exception as e:
                add_log(
                    title="[Camera] File write error",
                    content=f"Exception: {str(e)}",
                    label="warning"
                )
                return None

            add_log(
                title="[Camera] Screenshot captured",
                content=f"{filename}.jpg",
                label="agent",
                print=False
            )
            return filename

        except Exception as e:
            add_log(
                title="[Camera] Capture failed",
                content=f"Exception: {str(e)}",
                label="error"
            )
            return None

    async def _ensure_screenshot_directory(self):
        """Ensure the screenshot directory exists."""
        try:
            access_result = self.fs.access(self.screenshot_dir)
            if access_result is not None:
                try:
                    await access_result
                except TypeError:
                    pass
        except Exception:
            mkdir_result = self.fs.mkdir(self.screenshot_dir, {"recursive": True})
            if mkdir_result is not None:
                try:
                    await mkdir_result
                except TypeError:
                    pass

    def is_ready(self) -> bool:
        """Check if camera is ready for capture.

        Also attempts initialization if not yet done.

        Returns:
            True if ready
        """
        # Try to initialize if not yet attempted
        self._try_init()
        return self.ready
